### ISSUE TITLE
Push Notification delayed in android

### ISSUE THREAD

**Issue by JaganC** [driftyco/ionic-io-testers#2]
Hi,
  I am able to receive push Notifications in android using ionic, but its not received immediately. It takes hours to reach devices.

**Comment by ericb** [comment]
@JaganC As we were discussing earlier today, I think this is an issue with GCM/APNS sending your device the message, not with the push service. If you provide me with a message id, I can verify if it passed through our service in a timely manner.

**Comment by JaganC** [comment]
@ericb this is the latest Message ID "2f08eaa0310211e584b7bac97b714f68". Thanks

**Comment by ericb** [comment]
Yeah, the message was sent out almost immediately. If you didn't receive it for a few hours, there has to be some kind of delay on google or your device.

**Comment by JaganC** [comment]
@ericb Thanks. I'm scratching my head for this issue. I thought its a issue from my code.

**Comment by ericb** [comment]
I've never heard of anything like this beyond APNS taking 15-20 minutes sometimes to send a notification -- typically GCM sends messages out immediately so I'm not sure why your app could be having troubles. Maybe test out a new GCM project to see if something is just misconfigured there?

**Comment by JaganC** [comment]
@ericb I have tried with using new GCM id, but no luck. It continues the same behaviour. Especially when, we sending push for more than 1 devices. Is there any other way to solve this. Many Thanks.
